import { WEATHER } from "./constants.js";

export const BUILD_COST = Object.freeze({
  road: { wood: 1 },
  farm: { wood: 5 },
  lumber: { wood: 5 },
  warehouse: { wood: 10 },
  wall: { wood: 2 },
  erase: { wood: 0 },
});

export const CONSTRUCTION_BALANCE = Object.freeze({
  salvageRefundRatio: 0.5,
  worksiteAccessRadius: 2,
  warehouseRoadRadius: 1,
  warehouseSpacingRadius: 5,
  wallAnchorRadius: 1,
});

export const INITIAL_RESOURCES = Object.freeze({
  food: 55,
  wood: 70,
});

export const INITIAL_POPULATION = Object.freeze({
  workers: 18,
  visitors: 6,
  herbivores: 5,
  predators: 1,
});

export const WEATHER_MODIFIERS = Object.freeze({
  [WEATHER.CLEAR]: { moveCostMultiplier: 1.0, farmProductionMultiplier: 1.0, lumberProductionMultiplier: 1.0 },
  [WEATHER.RAIN]: { moveCostMultiplier: 1.15, farmProductionMultiplier: 1.0, lumberProductionMultiplier: 0.95 },
  [WEATHER.STORM]: { moveCostMultiplier: 1.3, farmProductionMultiplier: 0.8, lumberProductionMultiplier: 0.9 },
  [WEATHER.DROUGHT]: { moveCostMultiplier: 1.0, farmProductionMultiplier: 0.55, lumberProductionMultiplier: 1.0 },
  [WEATHER.WINTER]: { moveCostMultiplier: 1.25, farmProductionMultiplier: 0.65, lumberProductionMultiplier: 0.85 },
});

export const BALANCE = Object.freeze({
  hungerDecayPerSecond: 0.014,
  hungerEatRatePerSecond: 5.0,
  hungerEatRecoveryPerFoodUnit: 0.04,
  workerHungerDecayPerSecond: 0.0055,
  workerHungerSeekThreshold: 0.14,
  workerEatRecoveryTarget: 0.68,
  workerHungerEatRecoveryPerFoodUnit: 0.11,
  resourceCollapseCarryGrace: 0.5,
  visitorHungerDecayPerSecond: 0.0085,
  visitorHungerRecoveryPerSecond: 0.16,
  herbivoreHungerDecayPerSecond: 0.0095,
  herbivoreGrazeRecoveryPerSecond: 0.085,
  herbivoreGrazeSearchRadius: 8,
  herbivoreFarmAttractionBonus: 1.15,
  herbivoreHomeZoneBias: 0.68,
  herbivoreCoreAvoidancePenalty: 0.45,
  herbivoreFarmPressurePerSecond: 0.34,
  herbivoreFarmPressureDecayPerSecond: 0.16,
  ecologyFarmYieldPenaltyPerPressure: 0.44,
  ecologyFarmYieldPenaltyMax: 0.7,
  predatorHungerDecayPerSecond: 0.012,
  predatorHungerRecoveryOnHit: 0.24,
  predatorAttackDamage: 26,
  predatorAttackDistance: 0.9,
  predatorAttackCooldownSec: 1.4,
  predatorPatrolRefreshSec: 1.6,
  predatorFarmPressureAttraction: 1.05,
  predatorHomeZoneBias: 0.72,
  workerSpeed: 2.2,
  visitorSpeed: 1.95,
  herbivoreSpeed: 1.85,
  predatorSpeed: 2.25,
  boidsNeighborRadius: 1.9,
  boidsSeparationRadius: 0.9,
  boidsWeights: {
    separation: 1.4,
    alignment: 0.52,
    cohesion: 0.34,
    seek: 1.22,
  },
  boidsGroupProfiles: {
    workers: {
      neighborRadius: 1.65,
      separationRadius: 1.05,
      weights: { separation: 1.9, alignment: 0.18, cohesion: 0.08, seek: 1.28 },
    },
    traders: {
      neighborRadius: 1.55,
      separationRadius: 1.12,
      weights: { separation: 2.0, alignment: 0.16, cohesion: 0.06, seek: 1.35 },
    },
    saboteurs: {
      neighborRadius: 1.6,
      separationRadius: 1.1,
      weights: { separation: 2.08, alignment: 0.2, cohesion: 0.06, seek: 1.3 },
    },
    herbivores: {
      neighborRadius: 2.35,
      separationRadius: 0.9,
      weights: { separation: 1.25, alignment: 0.8, cohesion: 0.62, seek: 1.08 },
    },
    predators: {
      neighborRadius: 2.1,
      separationRadius: 0.86,
      weights: { separation: 1.35, alignment: 0.68, cohesion: 0.54, seek: 1.18 },
    },
  },
  managerIntervalSec: 1.2,
  foodEmergencyThreshold: 14,
  productionCooldownSec: 0.9,
  workerDeliverThreshold: 2.4,
  workerCarryPressureSec: 6,
  workerFarDepotDistance: 14,
  workerUnloadRatePerSecond: 4.2,
  warehouseQueuePenalty: 0.32,
  warehouseSoftCapacity: 3,
  worksiteCoverageSoftRadius: 10,
  worksiteCoverageHardRadius: 16,
  objectiveRoleBiasWeight: 0.58,
  objectiveFarmRatioMin: 0.18,
  objectiveFarmRatioMax: 0.82,
  objectiveHoldDecayPerSecond: 0.6,
  recoveryCooldownSec: 42,
  recoveryWindowSec: 16,
  recoveryChargeCap: 2,
  recoveryHintRiskThreshold: 68,
  recoveryTriggerRiskThreshold: 72,
  recoveryCriticalResourceThreshold: 4,
  recoveryCriticalProsperityThreshold: 22,
  recoveryCriticalThreatThreshold: 68,
  visitorTradeDepotZoneBonus: 0.65,
  visitorTradeConnectedRouteBonus: 0.55,
  visitorTradeWallBonusPerWall: 0.08,
  visitorTradeMaxWallBonus: 0.32,
  visitorTradeRoadNeighborBonus: 0.07,
  visitorTradeDistancePenalty: 0.05,
  sabotageFrontierZoneBonus: 0.65,
  sabotageDepotZoneBonus: 0.45,
  sabotageWarehousePriorityBonus: 0.35,
  sabotageRoadNeighborBonus: 0.12,
  sabotageWallPenaltyPerWall: 0.24,
  sabotageMaxWallPenalty: 0.72,
  sabotageDefenseBlockPerWall: 0.12,
  sabotageResistanceBlockWeight: 0.3,
  trafficSampleIntervalSec: 0.45,
  trafficSoftTileLoad: 2.15,
  trafficHotspotTileLoad: 3.2,
  trafficPenaltyPerLoad: 0.28,
  trafficNeighborPenaltyRatio: 0.46,
  trafficMaxPenaltyMultiplier: 2.2,
  trafficCrowdWeights: {
    worker: 1,
    visitor: 0.92,
    herbivore: 0.58,
    predator: 0.72,
  },
  sabotageCooldownMinSec: 7,
  sabotageCooldownMaxSec: 13,
  environmentDecisionIntervalSec: 12,
  policyDecisionIntervalSec: 10,
  policyTtlDefaultSec: 24,
  doctrineMasteryRewardMultiplier: 1.08,
  maxEventIntensity: 3,
  wildlifeSpawnRadiusBonus: 3,
  weatherPressureProsperityPenalty: 11.5,
  eventPressureProsperityPenalty: 7.2,
  contestedZoneProsperityPenalty: 1.6,
  weatherPressureThreat: 4.8,
  eventPressureThreat: 11.2,
  contestedZoneThreat: 3.4,
  banditRaidRouteBonus: 0.28,
  banditRaidDepotBonus: 0.22,
  banditRaidChokeBonus: 0.34,
  banditRaidWallMitigationPerWall: 0.06,
  banditRaidHazardPressureScale: 0.52,
  banditRaidLossPerPressure: 0.36,
  banditRaidSecondaryImpactPressure: 1.2,
  tradeCaravanDepotReadyBonus: 0.42,
  tradeCaravanConnectedRouteBonus: 0.24,
  tradeCaravanRoadSupportBonus: 0.055,
  tradeCaravanWallSafetyBonusPerWall: 0.05,
  tradeCaravanMaxWallSafetyBonus: 0.24,
  tradeCaravanHazardPenaltyPerPressure: 0.22,
  animalMigrationPressurePerHazard: 0.38,
  animalMigrationWildlifeZoneBonus: 0.18,
});
